# Generated by Django 6.0.3 on 2026-04-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='mois',
            new_name='periode',
        ),
        migrations.AddField(
            model_name='categorie',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='devise',
            field=models.CharField(choices=[('DH', 'Dirham'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='DH', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='frequence',
            field=models.CharField(blank=True, choices=[('journalier', 'Journalier'), ('mensuel', 'Mensuel'), ('hebdo', 'Hebdomadaire'), ('annuel', 'Annuel'), ('variable', 'Variable')], max_length=10, null=True),
        ),
    ]
