# Generated by Django 6.0.4 on 2026-05-06 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectif',
            options={'ordering': ['date_limite']},
        ),
        migrations.AddField(
            model_name='objectif',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectif',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='objectif',
            name='montant_cible',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='objectif',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='objectif',
            name='type',
            field=models.CharField(choices=[('epargne', "Objectif d'épargne"), ('limite', 'Limite de dépenses')], default='epargne', max_length=10),
        ),
    ]
