# Generated by Django 6.0.4 on 2026-05-06 11:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-periode']},
        ),
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='montant_limite',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'categorie', 'periode')},
        ),
    ]
